# Generated by Django 4.2.3 on 2023-10-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LlamaApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pinecone_indice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
