# Generated by Django 4.2.3 on 2023-10-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LlamaApp", "0002_pinecone_indice"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pinecone_indice",
            old_name="data",
            new_name="indices",
        ),
        migrations.AddField(
            model_name="pinecone_indice",
            name="idx_summaries",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
