# Generated by Django 4.2.3 on 2023-10-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LlamaApp", "0003_rename_data_pinecone_indice_indices_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pinecone_indice",
            name="indices",
        ),
        migrations.AddField(
            model_name="pinecone_indice",
            name="GPTVector",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pinecone_indice",
            name="path",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pinecone_indice",
            name="pinecone_title",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pinecone_indice",
            name="idx_summaries",
            field=models.TextField(),
        ),
    ]
