# Generated by Django 4.2.3 on 2023-10-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LlamaApp", "0004_remove_pinecone_indice_indices_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pinecone_indice",
            name="GPTVector",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="pinecone_indice",
            name="idx_summaries",
            field=models.JSONField(),
        ),
    ]
