# Generated by Django 4.2.3 on 2023-10-12 21:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("LlamaApp", "0005_alter_pinecone_indice_gptvector_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pinecone_indice",
            name="idx_summaries",
        ),
    ]
