# Generated by Django 4.2.3 on 2023-10-13 02:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("LlamaApp", "0006_remove_pinecone_indice_idx_summaries"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pinecone_indice",
            name="GPTVector",
        ),
    ]
